### ISSUE TITLE
execute 'yo easy-ui5 project' error

### ISSUE THREAD

**Issue by hanshixiongoutlook** [SAP/generator-easy-ui5#120]
## Easy-Ui5 version:3.5.1 

> Run `yo easy-ui5 --plugins` to print all relevant version strings

## Steps to reproduce the problem:
1.I want to generate a new project, but when i executed 'yo easy-ui5 project', it throwed an error
`quickstarter % yo easy-ui5 project

     _-----_     
    |       |    ╭──────────────────────────╮
    |--(o)--|    │  Welcome to the easy-ui5 │
   `---------´   │     3.5.1 generator!     │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? What do you want to do? Create a new OpenUI5/SAPUI5 project                          [app]
? How do you want to name this project? myUI5App
? Which namespace do you want to use? com.myorg
? Do you want to enable the SAP Fiori elements flexible programming model? No
? On which platform would you like to host the application? Application Router @ Cloud Foundry
? Which view type do you want to use? XML
? Where should your UI5 libs be served from? Content delivery network (SAPUI5)
? Would you like to create a new directory for the project? Yes
? Would you like to add JavaScript code assist libraries to the project? Yes
? Would you like to initialize a local git repository for the project? No
  ⚠ ️ patched @sap-ux's MainViewController.js to use ./BaseController
  ⚠ ️ patched @sap-ux's flpSandbox.html to boostrap only SAPUI5 (sap.ushell!)
used @sap-ux/fiori-freestyle-writer to generate freestyle app skeleton :)
  ⚠ ️ patched @sap-ux's index.html with Content delivery network (SAPUI5)
configuring app router settings...
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, scandir '/Users/I571366/workspace/quickstarter/com.myorg.myUI5App/uimodule/ui5-local.yaml'
    at Object.readdirSync (node:fs:1452:3)
    at exports.readdir (/Users/I571366/.npm/_generator-easy-ui5/plugin-generators/generator-ui5-project/node_modules/@mrmlnc/readdir-enhanced/lib/sync/fs.js:18:20)
    at Object.safeCall [as safe] (/Users/I571366/.npm/_generator-easy-ui5/plugin-generators/generator-ui5-project/node_modules/@mrmlnc/readdir-enhanced/lib/call.js:24:8)
    at DirectoryReader.readNextDirectory (/Users/I571366/.npm/_generator-easy-ui5/plugin-generators/generator-ui5-project/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:78:10)
    at DirectoryReader.stream._read (/Users/I571366/.npm/_generator-easy-ui5/plugin-generators/generator-ui5-project/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:57:18)
    at Readable.read (node:internal/streams/readable:496:12)
    at readdirSync (/Users/I571366/.npm/_generator-easy-ui5/plugin-generators/generator-ui5-project/node_modules/@mrmlnc/readdir-enhanced/lib/sync/index.js:27:21)
    at Function.readdirSyncStat (/Users/I571366/.npm/_generator-easy-ui5/plugin-generators/generator-ui5-project/node_modules/@mrmlnc/readdir-enhanced/lib/index.js:34:10)
    at ReaderSync.dynamicApi (/Users/I571366/.npm/_generator-easy-ui5/plugin-generators/generator-ui5-project/node_modules/yeoman-generator/node_modules/fast-glob/out/providers/reader-sync.js:64:24)
    at ReaderSync.api (/Users/I571366/.npm/_generator-easy-ui5/plugin-generators/generator-ui5-project/node_modules/yeoman-generator/node_modules/fast-glob/out/providers/reader-sync.js:56:25)
Emitted 'error' event on Readable instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: '/Users/I571366/workspace/quickstarter/com.myorg.myUI5App/uimodule/ui5-local.yaml'
}

Node.js v18.16.0
`

**Comment by nicoschoenteich** [comment]
Hi @hanshixiongoutlook,
please use Node.js v16 for now. Node.js v18 is not yet supported by `generator-ui5-project`, see this [PR](https://github.com/ui5-community/generator-ui5-project/pull/62).
Best, Nico
