### ISSUE TITLE
Error in add-extension 

### ISSUE THREAD

**Issue by felixSap** [SAP/generator-easy-ui5#139]
## Easy-Ui5 version:

> Run `yo easy-ui5 --plugins` to print all relevant version strings

## OS/version:
wsl Ubuntu 22.04.2 LTS

## Steps to reproduce the problem:

1. yo easy-ui5 add-extension

![Screenshot 2023-12-07 101816](https://github.com/SAP/generator-easy-ui5/assets/153177558/e95ea8b8-d265-4a9a-abdb-73b283e8fe92)
![Screenshot 2023-12-07 1019582](https://github.com/SAP/generator-easy-ui5/assets/153177558/18c22ae7-ef11-4139-9bc3-99189a60e0e2)

## What happens instead?

Error: Current environment doesn't provides some necessary feature this generator needs.
    at new Generator (/home/felix/.npm/_generator-easy-ui5/plugin-generators/generator-ui5-add-extension/node_modules/yeoman-generator/lib/index.js:259:13)
    at new App (/home/felix/.npm/_generator-easy-ui5/plugin-generators/generator-ui5-add-extension/generators/App.js:42:9)
    at FullEnvironment.instantiate (file:///home/felix/.nvm/versions/node/v18.18.2/lib/node_modules/yo/node_modules/yeoman-environment/dist/environment-base.js:252:27)
    at FullEnvironment.create (file:///home/felix/.nvm/versions/node/v18.18.2/lib/node_modules/yo/node_modules/yeoman-environment/dist/environment-base.js:246:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FullEnvironment.run (file:///home/felix/.nvm/versions/node/v18.18.2/lib/node_modules/yo/node_modules/yeoman-environment/dist/environment-full.js:307:27)

**Comment by petermuessig** [comment]
The subgenerator requires to use a proper version of `yeoman-environment`. I fixed this with the commit: https://github.com/ui5-community/generator-ui5-add-extension/commit/5b89d0170323bd8144ad0b5f516b9bdf3953f666
