### ISSUE TITLE
npm start failed

### ISSUE THREAD

**Issue by Hywfred** [SAP/generator-easy-ui5#95]
## Easy-Ui5 version:
```
Node.js: v16.14.0
yeoman-environment: 3.9.1
generator-easy-ui5: 3.2.2
home: /root/.nvm/versions/node/v16.14.0/lib/node_modules/generator-easy-ui5
pluginsHome: /root/.npm/_generator-easy-ui5/plugin-generators

Available generators:
  - generator-ui5-project: 0.1.1
```

## OS/version: 
SLES15-SP1

## Steps to reproduce the problem:

1. install `yo` and `generator-easy-ui5`
2. create your new project
3. `npm start`

## What is the expected result?
the project should start as expected, because I totally do the steps as instructions.

## What happens instead?
⚠️  Process Failed With Error

## Any other information? (attach screenshot if possible)
```
verb normalizer:projectPreprocessor Dependency of project @openui5/themelib_sap_fiori_3, "@openui5/sap.ui.unified": Distance to root of 2. Will be replaced by project with same ID and distance to root of undefined.
verb types:library:LibraryFormatter Could not find (optional) test directory of project @openui5/sap.ui.core: /root/.ui5/framework/packages/@openui5/sap.ui.core/1.96.0/test
verb types:library:LibraryFormatter Formatting library project sap.ui.core...
verb types:library:LibraryFormatter Ignoring 'test' directory for project sap.ui.core. Either no setting was provided or the path not found.
verb types:library:LibraryFormatter Could not find (optional) test directory of project @openui5/sap.ui.layout: /root/.ui5/framework/packages/@openui5/sap.ui.layout/1.96.0/test
verb types:library:LibraryFormatter Formatting library project sap.ui.layout...
verb types:library:LibraryFormatter Ignoring 'test' directory for project sap.ui.layout. Either no setting was provided or the path not found.
verb types:themeLibrary:ThemeLibraryFormatter Could not find (optional) test directory of project @openui5/themelib_sap_fiori_3: /root/.ui5/framework/packages/@openui5/themelib_sap_fiori_3/1.96.0/test
verb types:themeLibrary:ThemeLibraryFormatter Formatting theme-library project themelib_sap_fiori_3...
verb types:themeLibrary:ThemeLibraryFormatter Ignoring 'test' directory for project themelib_sap_fiori_3. Either no setting was provided or the path not found.
verb types:library:LibraryFormatter Could not find (optional) test directory of project @openui5/sap.m: /root/.ui5/framework/packages/@openui5/sap.m/1.96.0/test
verb types:library:LibraryFormatter Formatting library project sap.m...
verb types:library:LibraryFormatter Ignoring 'test' directory for project sap.m. Either no setting was provided or the path not found.
verb types:library:LibraryFormatter Namespace resolution from manifest.json failed for project sap.ui.layout: Could not find manifest.json file for project sap.ui.layout
verb types:library:LibraryFormatter Namespace resolution from .library failed for project sap.ui.layout: Could not find .library file for project sap.ui.layout
verb types:library:LibraryFormatter Failed to resolve namespace of project sap.ui.layout from manifest.json or .library file. Falling back to library.js file path...
verb types:library:LibraryFormatter Namespace resolution from .library failed for project sap.m: Could not find .library file for project sap.m
verb types:library:LibraryFormatter Namespace resolution from manifest.json failed for project sap.m: Could not find manifest.json file for project sap.m
verb types:library:LibraryFormatter Failed to resolve namespace of project sap.m from manifest.json or .library file. Falling back to library.js file path...
verb types:library:LibraryFormatter Namespace resolution from manifest.json failed for project sap.ui.core: Could not find manifest.json file for project sap.ui.core
verb types:library:LibraryFormatter Namespace resolution from .library failed for project sap.ui.core: Could not find .library file for project sap.ui.core
verb types:library:LibraryFormatter Failed to resolve namespace of project sap.ui.core from manifest.json or .library file. Falling back to library.js file path...
verb types:library:LibraryFormatter Deriving namespace for project sap.m from path of library.js file
verb types:library:LibraryFormatter Namespace of project sap.m is sap/m
verb types:library:LibraryFormatter No preload excludes defined in project configuration of framework library sap.m. Falling back to .library...

⚠️  Process Failed With Error

Error Message:
Could not find .library file for project sap.m

Stack Trace:
Error: Could not find .library file for project sap.m
    at /data/ui5/why.ui5Demo/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/types/library/LibraryFormatter.js:397:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async LibraryFormatter.getNamespaceFromDotLibrary (/data/ui5/why.ui5Demo/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/types/library/LibraryFormatter.js:251:42)
    at async Promise.all (index 1)
    at async LibraryFormatter.getNamespace (/data/ui5/why.ui5Demo/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/types/library/LibraryFormatter.js:115:8)
    at async LibraryFormatter.format (/data/ui5/why.ui5Demo/node_modules/@ui5/cli/node_modules/@ui5/builder/lib/types/library/LibraryFormatter.js:39:33)
    at async ProjectPreprocessor.applyType (/data/ui5/why.ui5Demo/node_modules/@ui5/cli/node_modules/@ui5/project/lib/projectPreprocessor.js:334:3)
    at async /data/ui5/why.ui5Demo/node_modules/@ui5/cli/node_modules/@ui5/project/lib/projectPreprocessor.js:92:7
    at async Promise.all (index 1)
    at async ProjectPreprocessor.processTree (/data/ui5/why.ui5Demo/node_modules/@ui5/cli/node_modules/@ui5/project/lib/projectPreprocessor.js:62:4)
    at async Object.generateProjectTree (/data/ui5/why.ui5Demo/node_modules/@ui5/cli/node_modules/@ui5/project/lib/normalizer.js:42:21)
    at async Object.serve.handler (/data/ui5/why.ui5Demo/node_modules/@ui5/cli/lib/cli/commands/serve.js:91:15)

If you think this is an issue of the UI5 Tooling, you might report it using the following URL: https://github.com/SAP/ui5-tooling/issues/new/choose
```

**Comment by Hywfred** [comment]
Hi,

I refer to https://github.com/SAP/openui5-sample-app/blob/master/ui5.yaml and changed framework version from `1.96.0` to `1.98.0`, then it succeeded. Maybe not compatible with the previous version. you might think about update the version info in the project. Thanks~

**Comment by nicogeburek** [comment]
Interesting. I can't reproduce that currently. Can you let me know what your exact configurations where when running the generator? A screen shot like this would be helpful:
<img width="641" alt="Screenshot 2022-02-11 at 10 09 58" src="https://user-images.githubusercontent.com/65965098/153564585-c8d6668b-53d6-4838-8889-7b0994a30c44.png">
